version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: habit-postgres
    restart: always
    environment:
      POSTGRES_DB: habitdb
      POSTGRES_USER: habituser
      POSTGRES_PASSWORD: habitpass
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: